<#import "../../freemarker/main-template.ftl" as u>

<@u.page>
<div class="page-header top5">
    <div class="row text-center">
        <div class="header-group">
            <h1>@Getter(lazy=true)</h1>

            <h3>Laziness is a virtue!</h3>
        </div>
    </div>
    <div class="row">
        <h3>Overview</h3>

        <p>
            <em>NEW IN Lombok 0.10: </em>You can let lombok generate a getter which will calculate a value once, the
            first time this getter is called, and cache it from then on. This can be useful if calculating the value
            takes a lot of CPU, or the value takes a lot of memory. To use this feature, create a <code>private
            final</code> variable, initialize it with the expression that's expensive to run, and annotate your
            field with <code>@Getter(lazy=true)</code>. The field will be hidden from the rest of your code, and the
            expression will be evaluated no more than once, when the getter is first called. There are no magic
            marker values (i.e. even if the result of your expensive calculation is <code>null</code>, the result is
            cached) and your expensive calculation need not be thread-safe, as lombok takes care of locking.
        </p>

    </div>
    <@u.comparison />
    <div class="row">
        <h3>Supported configuration keys (in addition to those listed on <a
                href="/features/details/getter-setter.html"><code>@Getter</code>'s main page</a>):</h3>
        <dl>
            <dt><code>lombok.getter.lazy.flagUsage</code> = [<code>warning</code> | <code>error</code>] (default:
                not set)
            </dt>
            <dd>Lombok will flag any usage of <code>@Getter(lazy=true)</code> as a warning or error if configured.
            </dd>
        </dl>
    </div>
    <div class="row">
        <h3>Small print</h3>

        <div class="smallprint">
            <p>
                You should never refer to the field directly, always use the getter generated by lombok, because the
                type of the field will be mangled into an <code>AtomicReference</code>. Do not try to directly
                access this <code>AtomicReference</code>; if it points to itself, the value has been calculated, and
                it is <code>null</code>. If the reference points to <code>null</code>, then the value has not been
                calculated. This behaviour may change in future versions. Therefore, <em>always</em> use the
                generated getter to access your field!
            </p>

            <p>
                Other Lombok annotations such as <code>@ToString</code> always call the getter even if you use
                <code>doNotUseGetters=true</code>.
            </p>
        </div>
    </div>
</div>

</@u.page>
