#!/bin/bash

if [ ! -e src/lombok/core/Version.java ]; then
	echo Run this script from the lombok project home directory.
	exit
fi

if [ ! -e dist/website.zip ]; then
	echo There is no dist/website.zip file! Run:
	echo ant website
	echo then restart this script
	exit
fi

mkdir -p build/temp || exit
cd build/temp || exit
git clone -l -n ../.. websitegit || exit
cd websitegit || exit
git branch gh-pages origin/gh-pages || exit
git checkout gh-pages || exit
rm -r * || exit
unzip ../../../dist/website.zip || exit
git add . || exit
git commit -a -m website || exit
git push origin gh-pages || exit
cd .. || exit
rm -rf websitegit || exit

echo Your gh-pages branch has been updated. Do not forget to run:
echo git push origin gh-pages
