/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <windows.h>
#include <stdio.h>
#include <winbase.h>
#include "lombok_installer_WindowsDriveInfo.h"

/*
 * Class:     lombok_installer_WindowsDriveInfo
 * Method:    getLogicalDrives0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lombok_installer_WindowsDriveInfo_getLogicalDrives0
  (JNIEnv *env, jobject obj) {
	return GetLogicalDrives();
}

/*
 * Class:     lombok_installer_WindowsDriveInfo
 * Method:    getDriveType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_lombok_installer_WindowsDriveInfo_getDriveType
  (JNIEnv *env, jobject obj, jstring drive) {
	const char *str= (*env)->GetStringUTFChars(env, drive, 0);
	DWORD val = GetDriveTypeA(str);
	(*env)->ReleaseStringUTFChars(env, drive, str);
	return val;
}
